markdown: redcarpet
highlighter: null
permalink: /:title

url: http://www.openkeychain.org
baseurl: 

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed